package cn.pzhu.jsj.pts.domain;

public class CodeAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_answer.id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_answer.question_id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_answer.input_data
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private String inputData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_answer.output_data
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private String outputData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_answer.id
     *
     * @return the value of code_answer.id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_answer.id
     *
     * @param id the value for code_answer.id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_answer.question_id
     *
     * @return the value of code_answer.question_id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_answer.question_id
     *
     * @param questionId the value for code_answer.question_id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_answer.input_data
     *
     * @return the value of code_answer.input_data
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public String getInputData() {
        return inputData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_answer.input_data
     *
     * @param inputData the value for code_answer.input_data
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setInputData(String inputData) {
        this.inputData = inputData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_answer.output_data
     *
     * @return the value of code_answer.output_data
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public String getOutputData() {
        return outputData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_answer.output_data
     *
     * @param outputData the value for code_answer.output_data
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setOutputData(String outputData) {
        this.outputData = outputData;
    }
}