package cn.pzhu.jsj.pts.domain;

import java.util.Date;

public class ExamPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.exam_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.create_time
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.id
     *
     * @return the value of exam_paper.id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.id
     *
     * @param id the value for exam_paper.id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.exam_id
     *
     * @return the value of exam_paper.exam_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.exam_id
     *
     * @param examId the value for exam_paper.exam_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.create_time
     *
     * @return the value of exam_paper.create_time
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.create_time
     *
     * @param createTime the value for exam_paper.create_time
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}