package cn.pzhu.jsj.pts.domain;

import java.util.Date;

public class Grade {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.score
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.student_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	private Integer studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.exam_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	private Integer examId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.paper_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	private Integer paperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.submit_time
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	private Date submitTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.id
	 * @return  the value of grade.id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.id
	 * @param id  the value for grade.id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.score
	 * @return  the value of grade.score
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.score
	 * @param score  the value for grade.score
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.student_id
	 * @return  the value of grade.student_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public Integer getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.student_id
	 * @param studentId  the value for grade.student_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.exam_id
	 * @return  the value of grade.exam_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public Integer getExamId() {
		return examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.exam_id
	 * @param examId  the value for grade.exam_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.paper_id
	 * @return  the value of grade.paper_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public Integer getPaperId() {
		return paperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.paper_id
	 * @param paperId  the value for grade.paper_id
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public void setPaperId(Integer paperId) {
		this.paperId = paperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.submit_time
	 * @return  the value of grade.submit_time
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public Date getSubmitTime() {
		return submitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.submit_time
	 * @param submitTime  the value for grade.submit_time
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}
}