package cn.pzhu.jsj.pts.domain;

public class PaperInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.type
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.question_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.paper_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.score
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.id
     *
     * @return the value of paper_info.id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.id
     *
     * @param id the value for paper_info.id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.type
     *
     * @return the value of paper_info.type
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.type
     *
     * @param type the value for paper_info.type
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.question_id
     *
     * @return the value of paper_info.question_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.question_id
     *
     * @param questionId the value for paper_info.question_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.paper_id
     *
     * @return the value of paper_info.paper_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.paper_id
     *
     * @param paperId the value for paper_info.paper_id
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.score
     *
     * @return the value of paper_info.score
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.score
     *
     * @param score the value for paper_info.score
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}