package cn.pzhu.jsj.pts.domain;

public class QuestionType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.type
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.name
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.description
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.type
     *
     * @return the value of question_type.type
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.type
     *
     * @param type the value for question_type.type
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.name
     *
     * @return the value of question_type.name
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.name
     *
     * @param name the value for question_type.name
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.description
     *
     * @return the value of question_type.description
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.description
     *
     * @param description the value for question_type.description
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }
}