package cn.pzhu.jsj.pts.domain;

public class SelectOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_option.id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_option.content
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_option.select_question_id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private Integer selectQuestionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_option.value
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_option.id
     *
     * @return the value of select_option.id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_option.id
     *
     * @param id the value for select_option.id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_option.content
     *
     * @return the value of select_option.content
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_option.content
     *
     * @param content the value for select_option.content
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_option.select_question_id
     *
     * @return the value of select_option.select_question_id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public Integer getSelectQuestionId() {
        return selectQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_option.select_question_id
     *
     * @param selectQuestionId the value for select_option.select_question_id
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setSelectQuestionId(Integer selectQuestionId) {
        this.selectQuestionId = selectQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_option.value
     *
     * @return the value of select_option.value
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_option.value
     *
     * @param value the value for select_option.value
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    public void setValue(String value) {
        this.value = value;
    }
}