package cn.pzhu.jsj.pts.domain;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.id
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.account
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.course_id
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private Integer courseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.pwd
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.class_name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.depart_name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	private String departName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.id
	 * @return  the value of student.id
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.id
	 * @param id  the value for student.id
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.account
	 * @return  the value of student.account
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.account
	 * @param account  the value for student.account
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.name
	 * @return  the value of student.name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.name
	 * @param name  the value for student.name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.course_id
	 * @return  the value of student.course_id
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.course_id
	 * @param courseId  the value for student.course_id
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.pwd
	 * @return  the value of student.pwd
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.pwd
	 * @param pwd  the value for student.pwd
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.class_name
	 * @return  the value of student.class_name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.class_name
	 * @param className  the value for student.class_name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.depart_name
	 * @return  the value of student.depart_name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public String getDepartName() {
		return departName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.depart_name
	 * @param departName  the value for student.depart_name
	 * @mbggenerated  Wed Apr 16 07:47:34 CST 2014
	 */
	public void setDepartName(String departName) {
		this.departName = departName;
	}
}