package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.CodeQuestion;
import cn.pzhu.jsj.pts.domain.CodeQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int countByExample(CodeQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int deleteByExample(CodeQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int insert(CodeQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int insertSelective(CodeQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	List<CodeQuestion> selectByExample(CodeQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	CodeQuestion selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByExampleSelective(@Param("record") CodeQuestion record,
			@Param("example") CodeQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByExample(@Param("record") CodeQuestion record,
			@Param("example") CodeQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByPrimaryKeySelective(CodeQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table code_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByPrimaryKey(CodeQuestion record);
}