package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.CodeAnswer;
import cn.pzhu.jsj.pts.domain.CodeAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int countByExample(CodeAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int deleteByExample(CodeAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int insert(CodeAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int insertSelective(CodeAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    List<CodeAnswer> selectByExample(CodeAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    CodeAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") CodeAnswer record, @Param("example") CodeAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByExample(@Param("record") CodeAnswer record, @Param("example") CodeAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByPrimaryKeySelective(CodeAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_answer
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByPrimaryKey(CodeAnswer record);
}