package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.ExamPaper;
import cn.pzhu.jsj.pts.domain.ExamPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int countByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int deleteByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int insert(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int insertSelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    List<ExamPaper> selectByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    ExamPaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByExample(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByPrimaryKeySelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByPrimaryKey(ExamPaper record);
}