package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.Exam;
import cn.pzhu.jsj.pts.domain.ExamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int countByExample(ExamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int deleteByExample(ExamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int insert(Exam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int insertSelective(Exam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	List<Exam> selectByExample(ExamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	Exam selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Exam record,
			@Param("example") ExamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int updateByExample(@Param("record") Exam record,
			@Param("example") ExamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int updateByPrimaryKeySelective(Exam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbggenerated  Wed May 07 15:57:43 CST 2014
	 */
	int updateByPrimaryKey(Exam record);
}