package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.PaperInfo;
import cn.pzhu.jsj.pts.domain.PaperInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int countByExample(PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int deleteByExample(PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int insert(PaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int insertSelective(PaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    List<PaperInfo> selectByExample(PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    PaperInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") PaperInfo record, @Param("example") PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByExample(@Param("record") PaperInfo record, @Param("example") PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByPrimaryKeySelective(PaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Fri Apr 18 23:58:47 CST 2014
     */
    int updateByPrimaryKey(PaperInfo record);
}