package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.SelectOption;
import cn.pzhu.jsj.pts.domain.SelectOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int countByExample(SelectOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int deleteByExample(SelectOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int insert(SelectOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int insertSelective(SelectOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    List<SelectOption> selectByExample(SelectOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    SelectOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") SelectOption record, @Param("example") SelectOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByExample(@Param("record") SelectOption record, @Param("example") SelectOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByPrimaryKeySelective(SelectOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_option
     *
     * @mbggenerated Mon Apr 14 15:03:25 CST 2014
     */
    int updateByPrimaryKey(SelectOption record);
}