package cn.pzhu.jsj.pts.mapper;

import cn.pzhu.jsj.pts.domain.SelectQuestion;
import cn.pzhu.jsj.pts.domain.SelectQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int countByExample(SelectQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int deleteByExample(SelectQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int insert(SelectQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int insertSelective(SelectQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	List<SelectQuestion> selectByExample(SelectQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	SelectQuestion selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByExampleSelective(@Param("record") SelectQuestion record,
			@Param("example") SelectQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByExample(@Param("record") SelectQuestion record,
			@Param("example") SelectQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByPrimaryKeySelective(SelectQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_question
	 * @mbggenerated  Fri Apr 18 23:58:47 CST 2014
	 */
	int updateByPrimaryKey(SelectQuestion record);
}